Squashed 'externals/fmt/' changes from f5e54359d..e69e5f977
e69e5f977 Update version
d88d016e2 Update changelog and version
b169f5be9 Restore symbol from 10.1
67c0c0c09 Update version
051b31531 Fix changelog update
b0569451a Bump version
ce3161887 Add overflow check
1a95e5d1b Update changelog
e1aac4266 Implement hex specifier
1705600be Remove optional
0c345dccd Bump actions/upload-artifact from 3.1.2 to 4.0.0 (#3782)
d33731d20 Implement empty format specs
c068c7c62 Add sentinel support
13fa26745 Update changelog
ebd5c8f99 Consistently use `fmt::` when invoking `format_to`. (#3779)
f5ca178c1 Complete scan_handler
138a64bfb Privatization
a5bacf3fe Remove custom_formatter
4aa24f54c Implement visitor for scan
e33c1568c Implement scan argument access
23826669c Cleanup error handling
8e6b2541a Apply coding conventions
4939d67a8 Cleanup scripts
bd3273021 Update release script
5f9058dbd Improve scripts
28576b060 Workaround github markdown mess
5ddd0cad1 Add a visitor for scan arguments
41d31512b Remove unused import
44b76d88f Fix docs
3324152db Update the release script
55190dadb Cleanup chrono test
63e4b93cf Update changelog
c64edcd32 Fix grammar
8c520b4fd Fix comment
2e6bb706b Update changelog
a13d1b12e Update changelog and docs
47a0eec2e Remove unnecessary alias
a8bed3895 Update changelog
e206043d2 Update changelog
4a6f0be5b Improve scan test
662d78415 Fix scan test
d5823aae3 Ceci n'est pas une pipe
d83c1b8d4 Add initial specifier support to scan
bfba2f9e9 Improve iterator handling in scan
a3bf40838 Initial range support in scan
ea1066bbe Cleanup test
be57ec7ec Fix chrono-test on platforms with 32-bit time_t
305747d44 Update changelog
47c8f63d0 Remove redundant specifier
76e8f1040 Update changelog
18ca2248d Document '?'
3a25a5848 Update README.md
4cbf6182e Remove peek
88d19f5de Cleanup scan
62529aad1 Apply coding conventions
df62c8678 Mark grow as deprecated
eef6dbafb Refactor file layer in scan
41c243335 clang-format
0a9d08fef Simplify fallback
e450b7aeb Implement locking
c5a85f8d7 Handle end of input in scan
1fd093add Update changelog
c4f2de493 Improve scan
d06921d8d Update changelog
fc0f84d29 Move formatbuf to ostream.h
86f2ec5de Fix a warning
a537c39fd Move conjunction to where it is used
7c240d52c Remove unused symbol
f64a6a2ec Update changelog
6f9a81678 Enable test
e7875ae0f Fix formatting of some nested ranges
3eb3aef57 Fix handling of set_debug_format
56d7a8c15 Simplify test
968fb9d16 Update changelog
b5f6b36b0 Update changelog
44dd6c0e0 Add glibc support to scan
3a0f4af4e Refactor file layer
1ca1a4a7a Update scan test
dbd9c89b3 Fix URI
9cd2b87e1 Fix wchar_t to char conversion warnings (#3764)
d5da9cc40 Apply clang-tidy
3a2c50d4a Cleanup test
18c43a214 Cleanup test
6b07fff0d Make hex float test more stable on different libc (#3762)
9165434e5 Enable consteval in MSVC VS2019 version 16.10 (#3757)
b8f81dede [StepSecurity] ci: Harden GitHub Actions (#3759)
923005bd4 Add stdlib version check for C++20 (#3754)
afa85e46c Apply clang-format
6025bd7c3 Add localized formatting to non-decimal presentation types of ints (#3750)
5471a2426 Update README.md
7d757cba5 CI: add lint github workflow for running clang-format (#3749)
6855bd532 Apply clang-format
bbee75357 Make clang-format happy
89860eb90 Use void(*)(void*) instead of decltype(&std::free) to satisfy clang in CUDA mode (#3751)
274ba2645 allow format_as() to format reference (#3739)
9048add99 Report out-of-range errors in chrono
640e0c02d Update README.md
6392dba21 Fix warning: identifier '_a' preceded by whitespace in a literal operator declaration is deprecated (#3748)
9a6fd11a5 Fix typo in gmock-gtest-all.cc (#3747)
dee0dbf07 Update README.md
2fabb43b9 Fix README file table (#3744)
9c3c107c8 Fix compile with GCC 6.3.0 (bug #3738) (#3743)
4497a2d09 fix cmake build
81629e425 Convert README to Markdown
6f95000b7 Update README.rst (#3737)
573d74395 error on bool arg w/ char pres_type (#3734)
5d55375a8 Experiment with scan buffering
71bd51e6c Implement `%j` specifier for `std::chrono::duration` (#3732)
f57508924 Simplify test
99b9fbf8e Add formatter for std::source_location (#3730)
8f83ee2ad Apply coding conventions
2a8a69446 Clarify that mixing code unit types is deprecated
04718008a Minor cleanup
b87ea22e2 Add native and generic representation for filesystem::path format spec (#3729)
5cfd28d47 Experiment with FILE in scan
73fae91e6 Cleanup .gitignore
6988be387 Bump version
2d1e4bb35 Remove a useless comment
7f8d41911 Fix overflow in time_point formatting with large dates (#3727)
ccc9ab7bf Include correct header
c4283ec47 Fix a libc++ warning and move the test to the right place
c3f9a7344 Apply coding conventions
06f1c0d72 Clarify that calling non-const format is deprecated
ffa5b14fe Make gtest-extra-test more portable
bea7ecc71 Disable locale-specific tests on OpenBSD
8a3938851 Fix the default locale in ostream_formatter
dd6f657a7 Remove this-> from decltype (#3723)
c13753a70 Fix handling of invalid Unicode in precision
864a8b5f3 fix: support optional<T> with format_as(T) (#3713)
649fe0fc8 Fix handling of null strings with the s specifier
45e124ee4 Added workaround for old xcode compiler bug (#3716)
045b05d79 Revert CMake changes
ec628561c Fix formatting
cbb18c237 Add support for CMake 3.28 C++  modules (#3679)
6b0082e6c Improve OpenBSD workaround
52a99a67f Set PDB path for Visual Studio (#3702)
4548d1eae Make write_escaped_path more portable
050d41e85 Make get_path_string more portable
1c023c008 Update bootstrap
b35d4e40f fix: use FMT_HAS_INCLUDE instead of __has_include
acaf83f40 feat: enable building with gcc 4.8
05aa78377 feat: include xlocale.h only if exists
05dda9490 Bump ossf/scorecard-action from 2.2.0 to 2.3.1 (#3697)
caf4fcb20 Bump github/codeql-action from 2.21.5 to 2.22.5 (#3696)
e0d3e346d Wrap Char in array to avoid pointer arithmetic (#3695)
19276d732 Fix an inconsistentcy between to_string and format
2a2c6e676 Fix flushing C++ iostreams before calling write_console() (#3689)
3b7f58a8b add buffer flush before direct write
e9bbd4069 Update README.rst
857cce7a8 Update README.rst
081d5b0d8 Update README.rst
baae1ed65 add meson instructions to usage docs (#3677)
2ac6c5ca8 Fix error C2668 on Windows with option /std:c++latest (#3680)
d9063baf2 Fix perf regression in ostream::print
f7542c576 Apply clang-format
130cf54cb Use a more sensible locale in tests
8e0ca0589 Use a more sensible locale in tests
bf497ac06 Cleanup test
bb8d50f04 add a suffix for days and fix the one for minutes (#3664)
f76603f21 fix: make std::bitset formattable again (#3660)
f91828936 Bump actions/checkout from 4.0.0 to 4.1.0 (#3666)
72e883e16 Diagnose unsupported code unit types
b3bf23f3c Remove leftover usage of the __std_stream header (#3663)
349e1c48d Update README.rst (#3661)
79dbd3f19 feat: add security policy to readme (#3655)
2dd4fa874 Remove an ostream hack incompatible with libc++ 17
44f3d8a77 README.rst: fix broken LICENSE link (#3653)
06b20387a Optimize fractional_part_rounding_thresholds
649f2460d Apply clang-format
7529af8f9 Workaround intel bug (#3652)
a3a74fa7f fix: mark fmt::streamed() as constexpr (#3650)
8ef4db4b9 Use datatype of underlying data (#3647)
492a99c96 Fix error: 'char_traits<custom_char>' is deprecated: char_traits<T> for T not equal to char, wchar_t, char8_t, char16_t or char32_t is non-standard and is provided for a temporary period. It will be removed in LLVM 18, so please migrate off of it. [-Werror,-Wdeprecated-declarations] (#3634)
3baaa8d89 Update docs
0e01e46c1 Implement nested formatter
f6ca4ea19 Avoid a space in the UDL definition (#3610)
a8a73da7e Add an option to avoid wchar APIs on Windows (#3636)
aa3c5a412 Clarify I/O error handling
bfdf50d18 Minor cleanup
571a9b7b2 Replace usage of C++17 library feature with C++11 (#3638)
6c088be8e Cleanup handling of visibility
016b1faed Fix symbol leak (#3627)
e25370093 Remove unnecessary spaces (#3642)
d4987546a Add an experimental nested formatter
5bdce181f Mark styled_arg as a view to prevent lifetime issues
a4b7b24b7 fix redundant redeclaration of ‘constexpr’ static data member (#3630)
fac60bd4f Remove type cast as mxe(mingw32) compiler complains about useless-cast (#3624)
f5be4a8a9 Bump actions/checkout from 3.5.3 to 4.0.0 (#3623)
84e666151 Workaround a gcc 6.4 issue
ac3240439 Update dependabot.yml
8894ae87f Bump github/codeql-action from 2.21.4 to 2.21.5 (#3622)
ca608547e Workaround a C++11 issue
23cf4055a Simplify URLs
46c8301ee Remove rst2md
a79a97982 Cleanup ranges test
457bb6a98 Merge the copyright comment since there are many contributors
61aef4111 Cleanup changelog
2a45fd30f Drop the rst suffix from the license file
24296cff1 Update ChangeLog.md
3d1d20a6a Update ChangeLog.md
0302c527c Update ChangeLog.md
154eccfeb Convert changelog to markdown for compatibility with release notes
35dc5def3 Revert "Bump actions/checkout from 3.5.3 to 3.6.0 (#3615)"
e1fc481d6 Merge the copyright comment since there are many contributors
e8259c529 Bump actions/checkout from 3.5.3 to 3.6.0 (#3615)
637925155 Update version
951fd9e66 Update changelog
be89b9a41 Merge branch 'release' of github.com:fmtlib/fmt
28e2d3b64 Bump version

git-subtree-dir: externals/fmt
git-subtree-split: e69e5f977d458f2650bb346dadf2ad30c5320281